- name: Update APT
  sudo: yes
  apt: update_cache=yes

- name: Install dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
      - wget
      - curl
      - gcc
      - libxml2-dev
      - libxslt-dev
      - libcurl4-openssl-dev
      - libreadline6-dev
      - libc6-dev
      - libssl-dev
      - make
      - build-essential
      - zlib1g-dev
      - openssh-server
      - git-core
      - libyaml-dev
      - postfix
      - libpq-dev
      - libicu-dev

- name: Add the gitlab_ci_runner user
  sudo: yes
  user: name=gitlab_ci_runner comment="GitLab CI Runner" groups=sudo shell=/bin/bash

- name: Install RVM
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

- name: Install Ruby {{ ruby_version }}
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: ~/.rvm/bin/rvm install --default {{ ruby_version }} creates=~/.rvm/rubies/{{ ruby_version }}

- name: Clone GitLab CI
  sudo: yes
  sudo_user: gitlab_ci_runner
  git: repo=https://github.com/gitlabhq/gitlab-ci-runner.git dest={{ install_path }} update=yes

- name: Install Ruby Gems
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: chdir={{ install_path }} /bin/bash --login -c 'gem install bundler && bundle install --deployment'

- name: Run GitLab CI Runner setup
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: chdir={{ install_path }} /bin/bash --login -c 'CI_SERVER_URL={{ ci_server }} REGISTRATION_TOKEN={{ ci_token }} bundle exec ./bin/setup'

- name: Add remote to known_hosts
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: ssh-keyscan {{ ci_ssh_server }} >> /home/gitlab_ci_runner/.ssh/known_hosts

- name: Install init.d
  sudo: yes
  command: cp -f {{ install_path }}/lib/support/init.d/gitlab_ci_runner /etc/init.d/gitlab-ci-runner

- name: Set service permissions
  sudo: yes
  file: src={{ install_path }}/lib/support/init.d/gitlab_ci_runner path=/etc/init.d/gitlab-ci-runner state=link owner=root group=root mode=0755 force=yes

- name: Install as boot service
  sudo: yes
  command: update-rc.d gitlab-ci-runner defaults 21
  notify:
      - start gitlab ci
