# Uses a temporary work around as described in ansible/#7284
# https://github.com/ansible/ansible/issues/7284

- name: Stop any runners
  sudo: yes
  command: service gitlab-ci-runner stop

- name: Update APT
  sudo: yes
  apt: update_cache=yes

- name: Install dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
      - wget
      - curl
      - gcc
      - libxml2-dev
      - libxslt-dev
      - libcurl4-openssl-dev
      - libreadline6-dev
      - libc6-dev
      - libssl-dev
      - make
      - build-essential
      - zlib1g-dev
      - openssh-server
      - git-core
      - libyaml-dev
      - postfix
      - libpq-dev
      - libicu-dev

- name: Add the gitlab_ci_runner user
  sudo: yes
  user: name=gitlab_ci_runner comment="GitLab CI Runner" groups=sudo shell=/bin/bash

- name: Install {{ ruby_version }}
  sudo: yes
  shell: creates=/usr/local/bin/ruby mkdir /tmp/ruby && cd /tmp/ruby && curl --progress ftp://ftp.ruby-lang.org/pub/ruby/2.0/{{ ruby_version }}.tar.gz | tar xz && cd {{ ruby_version }} && ./configure --disable-install-rdoc && make && sudo make install

- name: Clone GitLab CI {{ gitlab_version }}
  sudo: yes
  sudo_user: gitlab_ci_runner
  git: repo=https://github.com/gitlabhq/gitlab-ci-runner.git dest={{ install_path }} update=yes version={{ gitlab_version }}

- name: Install Ruby Gems
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: chdir={{ install_path }} sudo gem install bundler && sudo bundle install --deployment

- name: Check if SSH keys are presnt
  sudo: yes
  sudo_user: gitlab_ci_runner
  stat: path=/home/gitlab_ci_runner/.ssh/id_rsa
  register: ssh_keys
  ignore_errors: yes

- name: Do the SSH keys exist?
  debug: msg="Skipping runner configuration" var=ssh_keys.stat.exists
  when: ssh_keys.stat.exists

- name: Ensure .ssh present
  sudo: yes
  sudo_user: gitlab_ci_runner
  file: path=/home/gitlab_ci_runner/.ssh/ state=directory

- name: Add remote to known_hosts
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: ssh-keyscan {{ ci_ssh_server }} >> /home/gitlab_ci_runner/.ssh/known_hosts

- name: Run GitLab CI Runner setup
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: chdir={{ install_path }} CI_SERVER_URL={{ ci_server }} REGISTRATION_TOKEN={{ ci_token }} bundle exec ./bin/setup
  when: ssh_keys.stat.exists == false

- name: Set service permissions
  sudo: yes
  file: src={{ install_path }}/lib/support/init.d/gitlab_ci_runner path=/etc/init.d/gitlab-ci-runner state=link owner=root group=root mode=0755

- name: Install as boot service
  sudo: yes
  command: update-rc.d gitlab-ci-runner defaults 21

# Uses a temporary work around as described in ansible/#7284
# https://github.com/ansible/ansible/issues/7284

- name: Start runner
  sudo: yes
  command: service gitlab-ci-runner start
  when: start_runner
