- name: Update APT
  sudo: yes
  apt: update_cache=yes

- name: Install Dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
      - wget
      - curl
      - gcc
      - libxml2-dev
      - libxslt-dev
      - libcurl4-openssl-dev
      - libreadline6-dev
      - libc6-dev
      - libssl-dev
      - make
      - build-essential
      - zlib1g-dev
      - openssh-server
      - git-core
      - libyaml-dev
      - postfix
      - libpq-dev
      - libicu-dev

- name: Install Ruby 2.0
  sudo: yes
  shell: mkdir /tmp/ruby && cd /tmp/ruby && curl --progress ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p353.tar.gz | tar xz && cd ruby-2.0.0-p353 && ./configure --disable-install-rdoc && make && sudo make install creates=/opt/ruby/bin/ruby
