- name: Update APT
  sudo: yes
  apt: update_cache=yes

- name: Install dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
      - wget
      - curl
      - gcc
      - libxml2-dev
      - libxslt-dev
      - libcurl4-openssl-dev
      - libreadline6-dev
      - libc6-dev
      - libssl-dev
      - make
      - build-essential
      - zlib1g-dev
      - openssh-server
      - git-core
      - libyaml-dev
      - postfix
      - libpq-dev
      - libicu-dev

- name: Install Ruby 2.0
  sudo: yes
  shell: creates=/usr/local/bin/ruby mkdir /tmp/ruby && cd /tmp/ruby && curl --progress ftp://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p353.tar.gz | tar xz && cd ruby-2.0.0-p353 && ./configure --disable-install-rdoc && make && sudo make install

- name: Add the gitlab_ci_runner user
  sudo: yes
  user: name=gitlab_ci_runner comment="GitLab CI Runner" groups=sudo shell=/bin/bash

- name: Clone GitLab CI
  sudo: yes
  sudo_user: gitlab_ci_runner
  git: repo=https://github.com/gitlabhq/gitlab-ci-runner.git dest={{ install_path }} update=yes

#- name: Install Ruby Gems
#  sudo: yes
#  sudo_user: gitlab_ci_runner
#  shell: chdir={{ install_path }} gem install bundler -N --user-install && BUNDLE_PATH={{ gem_path }} {{ gem_path }}/bundle install --deployment

#- name: Run GitLab CI Runner setup
#  sudo: yes
#  sudo_user: gitlab_ci_runner
#  shell: chdir={{ install_path }} BUNDLE_PATH={{ gem_path }} CI_SERVER_URL={{ ci_server }} REGISTRATION_TOKEN={{ ci_token }} {{ gem_path }}/bundle exec ./bin/setup

- name: Add remote to known_hosts
  sudo: yes
  sudo_user: gitlab_ci_runner
  shell: ssh-keyscan {{ ci_ssh_server }} >> /home/gitlab_ci_runner/.ssh/known_hosts

- name: Install init.d
  sudo: yes
  template: src=init.d.j2 dest=/etc/init.d/gitlab-ci-runner mode=0755 owner=root group=root

- name: Install as service
  sudo: yes
  command: update-rc.d gitlab-ci-runner defaults 21
  notify:
      - start gitlab ci
